from django.urls import path
from .views import (
    AuthForgotPasswordView,
    AuthLoginView,
    AuthLogoutView,
    AuthMeView,
    BurndownReportView,
    ChatChannelCreateView,
    ChatChannelDetailView,
    ChatChannelMemberAddView,
    ChatChannelMemberRemoveView,
    ChatDirectMessageCreateView,
    ChatMessageDetailView,
    ChatRoomListView,
    ChatRoomMessagesView,
    ChatRoomReadView,
    DashboardReportView,
    EpicDetailView,
    EpicsView,
    IssueCommentCreateView,
    IssueCommentDetailView,
    IssueAttachmentDeleteView,
    IssueAttachmentUploadView,
    IssueDetailView,
    IssueLinkCreateView,
    IssueLinkDeleteView,
    IssueLogTimeView,
    IssueMoveView,
    IssuesView,
    IssueWatchToggleView,
    LabelsView,
    NotificationListView,
    NotificationMarkReadView,
    NotificationReadAllView,
    NotificationUnreadCountView,
    PlatformSetupInstructionDetailView,
    PlatformSetupInstructionListCreateView,
    ProjectDetailView,
    ProjectListView,
    ProjectOnboardingView,
    SprintCompleteView,
    SprintDetailView,
    SprintStartView,
    SprintsView,
    UsersListView,
    UserDetailView,
    VelocityReportView,
)

urlpatterns = [
    path('auth/login/', AuthLoginView.as_view()),
    path('auth/forgot-password/', AuthForgotPasswordView.as_view()),
    path('auth/logout/', AuthLogoutView.as_view()),
    path('auth/me/', AuthMeView.as_view()),

    path('users/', UsersListView.as_view()),
    path('users/<str:user_uid>/', UserDetailView.as_view()),

    path('notifications/', NotificationListView.as_view()),
    path('notifications/unread-count/', NotificationUnreadCountView.as_view()),
    path('notifications/read-all/', NotificationReadAllView.as_view()),
    path('notifications/<str:notification_uid>/read/', NotificationMarkReadView.as_view()),

    path('chat/rooms/', ChatRoomListView.as_view()),
    path('chat/dms/', ChatDirectMessageCreateView.as_view()),
    path('chat/channels/', ChatChannelCreateView.as_view()),
    path('chat/channels/<str:room_uid>/', ChatChannelDetailView.as_view()),
    path('chat/channels/<str:room_uid>/members/', ChatChannelMemberAddView.as_view()),
    path('chat/channels/<str:room_uid>/members/<str:user_uid>/', ChatChannelMemberRemoveView.as_view()),
    path('chat/rooms/<str:room_uid>/messages/', ChatRoomMessagesView.as_view()),
    path('chat/messages/<str:message_uid>/', ChatMessageDetailView.as_view()),
    path('chat/rooms/<str:room_uid>/read/', ChatRoomReadView.as_view()),

    path('projects/', ProjectListView.as_view()),
    path('projects/<str:project_uid>/', ProjectDetailView.as_view()),
    path('projects/<str:project_uid>/onboarding/', ProjectOnboardingView.as_view()),
    path('projects/<str:project_uid>/onboarding/instructions/', PlatformSetupInstructionListCreateView.as_view()),
    path('onboarding-instructions/<str:instruction_uid>/', PlatformSetupInstructionDetailView.as_view()),

    path('labels/', LabelsView.as_view()),

    path('epics/', EpicsView.as_view()),
    path('epics/<str:epic_uid>/', EpicDetailView.as_view()),

    path('sprints/', SprintsView.as_view()),
    path('sprints/<str:sprint_uid>/', SprintDetailView.as_view()),
    path('sprints/<str:sprint_uid>/start/', SprintStartView.as_view()),
    path('sprints/<str:sprint_uid>/complete/', SprintCompleteView.as_view()),

    path('issues/', IssuesView.as_view()),
    path('issues/<str:issue_uid>/', IssueDetailView.as_view()),
    path('issues/<str:issue_uid>/move/', IssueMoveView.as_view()),
    path('issues/<str:issue_uid>/comments/', IssueCommentCreateView.as_view()),
    path('issues/<str:issue_uid>/comments/<str:comment_uid>/', IssueCommentDetailView.as_view()),
    path('issues/<str:issue_uid>/log-time/', IssueLogTimeView.as_view()),
    path('issues/<str:issue_uid>/watch-toggle/', IssueWatchToggleView.as_view()),
    path('issues/<str:issue_uid>/links/', IssueLinkCreateView.as_view()),
    path('issues/<str:issue_uid>/links/<str:link_uid>/', IssueLinkDeleteView.as_view()),
    path('issues/<str:issue_uid>/attachments/', IssueAttachmentUploadView.as_view()),
    path('issues/<str:issue_uid>/attachments/<str:attachment_uid>/', IssueAttachmentDeleteView.as_view()),

    path('reports/dashboard/', DashboardReportView.as_view()),
    path('reports/burndown/', BurndownReportView.as_view()),
    path('reports/velocity/', VelocityReportView.as_view()),
]
